// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2-FwaHuWJ9-DVgxWyMO9sVhIAazVbrRQ',
    appId: '1:1055619091454:web:83353dc3f950c989de4eaf',
    messagingSenderId: '1055619091454',
    projectId: 'coba-cd-flutter-a19f4',
    authDomain: 'coba-cd-flutter-a19f4.firebaseapp.com',
    storageBucket: 'coba-cd-flutter-a19f4.firebasestorage.app',
    measurementId: 'G-29KECWB7ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3cg_nLDwIaZqrfyS30wWPW47dwwRK5Wo',
    appId: '1:1055619091454:android:91bd19d58fa34bdede4eaf',
    messagingSenderId: '1055619091454',
    projectId: 'coba-cd-flutter-a19f4',
    storageBucket: 'coba-cd-flutter-a19f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Sz_f4CwgfE9ghLzvF_Lrw_1A8kZwYZ4',
    appId: '1:1055619091454:ios:07ddd281b7a96ae4de4eaf',
    messagingSenderId: '1055619091454',
    projectId: 'coba-cd-flutter-a19f4',
    storageBucket: 'coba-cd-flutter-a19f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Sz_f4CwgfE9ghLzvF_Lrw_1A8kZwYZ4',
    appId: '1:1055619091454:ios:07ddd281b7a96ae4de4eaf',
    messagingSenderId: '1055619091454',
    projectId: 'coba-cd-flutter-a19f4',
    storageBucket: 'coba-cd-flutter-a19f4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2-FwaHuWJ9-DVgxWyMO9sVhIAazVbrRQ',
    appId: '1:1055619091454:web:62b0a3ce1a570633de4eaf',
    messagingSenderId: '1055619091454',
    projectId: 'coba-cd-flutter-a19f4',
    authDomain: 'coba-cd-flutter-a19f4.firebaseapp.com',
    storageBucket: 'coba-cd-flutter-a19f4.firebasestorage.app',
    measurementId: 'G-6VRS8Y0P9Y',
  );
}
